import * as z3 from "z3-solver";

class FirefoxRandomnessPredictor {
  #isUnsat = false;
  #mask = 0xffffffffffffffffn;
  #seState0: z3.BitVec | undefined;
  #seState1: z3.BitVec | undefined;
  #s0Ref: z3.BitVec | undefined;
  #s1Ref: z3.BitVec | undefined;
  #solver: z3.Solver | undefined;
  #context: z3.Context | undefined;
  #concreteState0 = 0n;
  #concreteState1 = 0n;

  sequence: number[] = [];

  // Mimic static class
  private constructor() {}

  /**
   * Predict next random number.
   * @returns {number}
   */
  public predictNext(): number {
    if (this.#isUnsat) {
      throw new Error("Current state is unsatisfiable!");
    }
    return this.#toDouble(this.#xorShift128PlusConcrete());
  }

  /**
   * Pseudo constructor (since we can't have async constructors).
   * This allows us to generate concrete state from symbolic state so we can
   * use a concrete XOR algo to continue predicting random values without
   * using z3/symbolic state. Z3/symbolic state is more resoure intensive
   * and takes longer.
   * @param {number[]} sequence : Floats generated by `Math.random()`
   * @returns
   */
  static async create(sequence: number[]): Promise<FirefoxRandomnessPredictor> {
    try {
      const self = new FirefoxRandomnessPredictor();
      self.sequence = sequence;
      const { Context } = await z3.init();
      self.#context = Context("main");
      self.#solver = new self.#context.Solver();
      self.#seState0 = self.#context.BitVec.const("se_state0", 64);
      self.#seState1 = self.#context.BitVec.const("se_state1", 64);
      self.#s0Ref = self.#seState0;
      self.#s1Ref = self.#seState1;

      for (let i = 0; i < self.sequence.length; i++) {
        self.#xorShift128PlusSymbolic();
        const mantissa = self.#recoverMantissa(self.sequence[i]);
        const state = self.#seState0.add(self.#seState1).and(self.#context!.BitVec.val(0x1fffffffffffff, 64));
        self.#solver.add(state.eq(self.#context.BitVec.val(mantissa, 64)));
      }

      const check = await self.#solver.check();
      if (check !== "sat") {
        self.#isUnsat = true;
        return self;
      }

      const model = self.#solver.model();
      self.#concreteState0 = (model.get(self.#s0Ref) as z3.BitVecNum).value();
      self.#concreteState1 = (model.get(self.#s1Ref) as z3.BitVecNum).value();

      // We have to get our concrete state up to the same point as our symbolic state,
      // therefore, we discard as many "predictNext()" calls as we have `self.sequence.length`
      // Otherwise, we would return random numbers to the caller that they already have.
      // Now, when we return from predictNext() we get the actual next.
      for (let i = 0; i < self.sequence.length; i++) {
        self.predictNext();
      }
      return Promise.resolve(self);
    } catch (e) {
      return Promise.reject(e);
    }
  }

  #xorShift128PlusSymbolic() {
    if (this.#seState0 === undefined || this.#seState1 === undefined) {
      throw new Error("States are not defined!");
    }
    let s1 = this.#seState0;
    let s0 = this.#seState1;
    s1 = s1.xor(s1.shl(23));
    s1 = s1.xor(s1.lshr(17));
    s1 = s1.xor(s0);
    s1 = s1.xor(s0.lshr(26));
    this.#seState0 = this.#seState1;
    this.#seState1 = s1;
  }

  #xorShift128PlusConcrete(): bigint {
    let s1 = this.#concreteState0 & this.#mask;
    let s0 = this.#concreteState1 & this.#mask;
    s1 ^= (s1 << 23n) & this.#mask;
    s1 ^= (s1 >> 17n) & this.#mask;
    s1 ^= s0 & this.#mask;
    s1 ^= (s0 >> 26n) & this.#mask;
    this.#concreteState0 = s0 & this.#mask;
    this.#concreteState1 = s1 & this.#mask;
    return (this.#concreteState0 + this.#concreteState1) & this.#mask;
  }

  #recoverMantissa(double: number): bigint {
    return BigInt(Math.floor(double * Math.pow(2, 53)));
  }

  #toDouble(n: bigint): number {
    return Number(n & 0x1fffffffffffffn) / Number(1n << 53n);
  }
}

export default FirefoxRandomnessPredictor;
